codo-kerrigan:
  restart: unless-stopped
  image: codo_dns_image
  volumes:
    - /var/log/supervisor/:/var/log/supervisor/
    - /opt/ops_scripts:/opt/ops_scripts
    - /sys/fs/cgroup:/sys/fs/cgroup
  ports:
    - "8060:80"
